services:
  redis:
    image: redis:7-alpine
    container_name: shopai-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  shopai:
    image: baekgiwhan/shopai:latest
    env_file: .env
    ports:
      - '3030:3030'
    restart: always
    depends_on:
      - redis

volumes:
  redis_data: